{
 "title": "Basic Device Monitoring | Nvidia Jetson",
 "description": "A Grafana dashboard driven by a Prometheus metrics collector for monitoring NVIDIA Jetson devices",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Introduction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Uptime | Hours",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "uptime / 3600" }
   ]
  },
  {
   "title": "Board Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "python_info{implementation=\"CPython\",major=\"3\",minor=\"10\",patchlevel=\"4\",version=\"3.10.4\"}"
    }
   ]
  },
  {
   "title": "Board Hardware Info",
   "type": "text",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 4 },
   "options": {
    "content": " - GPU:\tNVIDIA Maxwell architecture with 128 NVIDIA CUDA® cores\n\n - CPU: \tQuad-core ARM Cortex-A57 MPCore processor\n\n - Memory: \t4 GB 64-bit LPDDR4, 1600MHz 25.6 GB/s\n\n - Storage: \t32 GB eMMC 5.1"
   },
   "targets": [
    { "expr": "jetson_info_hardware_info" }
   ]
  },
  { "title": "Basic Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "GPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_utilization_percentage" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu" }
   ]
  },
  {
   "title": "RAM Used",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ram{statistic=\"used\"} * 1000"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk{mountpoint=\"/etc/resolv.conf\",statistic=\"percent\"}"
    }
   ]
  },
  { "title": "Thermals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Sensor Temperature | A0",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 1, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{machine_part=\"AO\"}"
    }
   ]
  },
  {
   "title": "Sensor Temperature | PLL",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{machine_part=\"PLL\"}"
    }
   ]
  },
  {
   "title": "Sensor Temperature | GPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{machine_part=\"GPU\"}"
    }
   ]
  },
  {
   "title": "Fan",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jetson_usage_fan" }
   ]
  },
  {
   "title": "Sensor Temperature | CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{machine_part=\"CPU\"}"
    }
   ]
  },
  {
   "title": "Sensor Temperature | PMIC",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{machine_part=\"PMIC\"}"
    }
   ]
  },
  {
   "title": "Sensor Temperature | WiFi",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{machine_part=\"iwlwifi\"}"
    }
   ]
  },
  {
   "title": "Sensor Temperature | Thermal",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{machine_part=\"thermal\"}"
    }
   ]
  },
  { "title": "Power Characteristics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Power | 5V IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltage{source=\"POM_5V_IN\"}"
    }
   ]
  },
  {
   "title": "Power | 5V GPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltage{source=\"POM_5V_GPU\"}"
    }
   ]
  },
  {
   "title": "Power | 5V CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltage{source=\"POM_5V_CPU\"}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jetson_usage_power" }
   ]
  },
  { "title": "Processing Loads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Core #1 | Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 40 },
   "targets": [
    {
     "expr": "cpu{core=\"1\",statistic=\"status\"} "
    }
   ]
  },
  {
   "title": "Core #2 | Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 13, "y": 40 },
   "targets": [
    {
     "expr": "cpu{core=\"2\",statistic=\"status\"} "
    }
   ]
  },
  {
   "title": "Core #1 | Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 46 },
   "targets": [
    {
     "expr": "cpu{core=\"1\",statistic=\"freq\"} "
    }
   ]
  },
  {
   "title": "Core #2 | Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 13, "y": 46 },
   "targets": [
    {
     "expr": "cpu{core=\"2\",statistic=\"freq\"} "
    }
   ]
  },
  {
   "title": "Core #1 | Val",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 52 },
   "targets": [
    {
     "expr": "cpu{core=\"1\",statistic=\"val\"} "
    }
   ]
  },
  {
   "title": "Core #2 | Val",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 13, "y": 52 },
   "targets": [
    {
     "expr": "cpu{core=\"2\",statistic=\"val\"} "
    }
   ]
  },
  { "title": "Alerts | CPU", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Core #3 | Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 66 },
   "targets": [
    {
     "expr": "cpu{core=\"3\",statistic=\"status\"} "
    }
   ]
  },
  {
   "title": "Core #4 | Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 13, "y": 66 },
   "targets": [
    {
     "expr": "cpu{core=\"4\",statistic=\"status\"} "
    }
   ]
  },
  {
   "title": "Core #3 | Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 72 },
   "targets": [
    {
     "expr": "cpu{core=\"3\",statistic=\"freq\"} "
    }
   ]
  },
  {
   "title": "Core #4 | Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 13, "y": 72 },
   "targets": [
    {
     "expr": "cpu{core=\"4\",statistic=\"freq\"} "
    }
   ]
  },
  {
   "title": "Core #3 | Val",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 78 },
   "targets": [
    {
     "expr": "cpu{core=\"3\",statistic=\"val\"} "
    }
   ]
  },
  {
   "title": "Core #4 | Val",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 13, "y": 78 },
   "targets": [
    {
     "expr": "cpu{core=\"4\",statistic=\"val\"} "
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collection | Generation 0",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 5, "y": 6 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Collection | Generation 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 5, "y": 14 },
     "targets": [
      {
       "expr": "python_gc_objects_collected_total{generation=\"1\"}"
      }
     ]
    },
    {
     "title": "Collection | Generation 2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 5, "y": 22 },
     "targets": [
      {
       "expr": "python_gc_objects_collected_total{generation=\"2\"}"
      }
     ]
    }
   ]
  }
 ]
}